language: python
python: 3.5
cache: pip
env:
    - TOX_ENV="py27"
    - TOX_ENV="py33"
    - TOX_ENV="py34"
    - TOX_ENV="py35"
    - TOX_ENV="pylint"
    - TOX_ENV="style"
install:
    pip install tox
script:
    - tox -e $TOX_ENV
