version: "{branch}-{build}"
cache:
    - '%LOCALAPPDATA%\pip\Cache'
build: off

skip_tags: true

shallow_clone: true
clone_depth: 100

environment:
    matrix:
        - PYTHON: C:\Python27
          TOXENV: "py27-{pure,native}"

        - PYTHON: C:\Python33
          TOXENV: "py33-{pure,native}"

        - PYTHON: C:\Python34
          TOXENV: "py34-{pure,native}"

        - PYTHON: C:\Python35
          TOXENV: "py35-{pure,native}"

        - PYTHON: C:\Python27-x64
          TOXENV: "py27-{pure,native}"

        - PYTHON: C:\Python33-x64
          TOXENV: "py33-{pure,native}"

        - PYTHON: C:\Python34-x64
          TOXENV: "py34-{pure,native}"

        - PYTHON: C:\Python35-x64
          TOXENV: "py35-{pure,native}"


init:
    - ps: echo $env:TOXENV
    - ps: ls C:\Python*

install:
    - '%PYTHON%\Scripts\pip install tox'
    - '%PYTHON%\Scripts\pip install wheel'
    - '%PYTHON%\Scripts\pip install cython'

test_script:
    - "build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
    - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
    - path: dist\*

on_failure:
    - ps: dir "env:"
    - ps: get-content .tox\*\log\*
